name: fasum
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_database: ^11.3.5
  firebase_auth: ^5.5.3
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0
  geolocator: ^14.0.0
  cloud_firestore: ^5.6.7
  intl: ^0.20.2
  url_launcher: ^6.3.1
  flutter_launcher_icons: ^0.14.3
  shimmer: ^3.0.0
  flutter_local_notifications: ^19.2.1
  google_generative_ai: ^0.4.7
  firebase_messaging: ^15.2.5

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/fasum_icon_splas.png"
  min_sdk_android: 23

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
