// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs90C0jF78kQcPI_zkqOCKFGe1Im2aqLk',
    appId: '1:928749756845:web:56fb5ca99ee8b5ee5c4124',
    messagingSenderId: '928749756845',
    projectId: 'fasum-b9e1e',
    authDomain: 'fasum-b9e1e.firebaseapp.com',
    storageBucket: 'fasum-b9e1e.firebasestorage.app',
    measurementId: 'G-1986T1SCTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBDV_e_3U7ucpxllBRoiazcoLpyzOs8m8',
    appId: '1:928749756845:android:647b80c0fb356eae5c4124',
    messagingSenderId: '928749756845',
    projectId: 'fasum-b9e1e',
    storageBucket: 'fasum-b9e1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9E8-2wXi71Zk5nQo5Hrkns3wnCXoxjlM',
    appId: '1:928749756845:ios:dcc2e96f0d17d3b85c4124',
    messagingSenderId: '928749756845',
    projectId: 'fasum-b9e1e',
    storageBucket: 'fasum-b9e1e.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9E8-2wXi71Zk5nQo5Hrkns3wnCXoxjlM',
    appId: '1:928749756845:ios:dcc2e96f0d17d3b85c4124',
    messagingSenderId: '928749756845',
    projectId: 'fasum-b9e1e',
    storageBucket: 'fasum-b9e1e.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs90C0jF78kQcPI_zkqOCKFGe1Im2aqLk',
    appId: '1:928749756845:web:c3ae461889623d765c4124',
    messagingSenderId: '928749756845',
    projectId: 'fasum-b9e1e',
    authDomain: 'fasum-b9e1e.firebaseapp.com',
    storageBucket: 'fasum-b9e1e.firebasestorage.app',
    measurementId: 'G-WCBNS79L6Y',
  );
}
